defaults:
  - biovision: defaults

cxr_filepath: 'data/cxr.h5'
txt_filepath: 'data/mimic_impressions.csv'
model_path: None
batch_size: 16
epochs: 3
lr: 1e-4
save_interval: 1000
log_interval: 10
save_dir: "./checkpoints/" 
seed: 1234
optimizer: "sgd"
momentum: 0.9
context_length: 77
random_init: False
model_name: "uU"
use_cxrbert: True
lock_text: False
lock_vision: False